name: zabbix-test
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  run:
    name: Run
    env:
      TEST_ZABBIX_USER: Admin
      TEST_ZABBIX_PASSWORD: zabbix
      TEST_ZABBIX_HOST: localhost
      TEST_ZABBIX_URL: http://$TEST_ZABBIX_HOST/api_jsonrpc.php
      TEST_ZABBIX_VERSION: 6.0.2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.1' 
      
      - name: Check golang version
        run: go version

      - name: Preparation steps
        run: | 
          sudo hostname $TEST_ZABBIX_HOST && echo "127.0.1.1    $TEST_ZABBIX_HOST" | sudo tee -a /etc/hosts
          sudo apt update -q
          sudo apt install -y python-pip python-dev jq
          sudo -H pip install ansible==2.5.3

      - name: Set up zabbix test environment
        run: |
          ansible-galaxy install dj-wasabi.zabbix-server
          ansible-galaxy install dj-wasabi.zabbix-web
          cat <<-EOF | head -n -2 > deploy.yml
            - hosts: $TEST_ZABBIX_HOST
              become: yes
              roles:
                - { role: geerlingguy.apache }
                - { role: dj-wasabi.zabbix-server }
                - { role: dj-wasabi.zabbix-web }
              vars:
                - database_type: mysql
                - database_type_long: mysql
                - zabbix_server_database: mysql
                - zabbix_server_database_long: mysql
                - zabbix_server_dbport: 3306
                - zabbix_server_mysql_login_host: $TEST_ZABBIX_HOST
                - zabbix_server_mysql_login_user: root
                - zabbix_url: $TEST_ZABBIX_HOST
                - zabbix_version: $TEST_ZABBIX_VERSION
            EOF
          ansible-playbook -c local -i "$TEST_ZABBIX_HOST," deploy.yml
          go install github.com/extrading/go-zabbix-api

      - name: Run tests
        run: bash -x tests.sh
      

      

     